name: hotel-id-nns
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia # remove if on cpu only
dependencies:
  - python=3.9
  - yapf
  - ca-certificates
  - openssl
  - torchvision>=0.14
  - pytorch>=1.13
  - pytorch-cuda=11.7 # or cpuonly 
  - h5py
  - pip>=22
  - dvc
  - dvc-s3
  - auto-sklearn
  - wandb
  - pandas
  - matplotlib
  - pytables
  - ipykernel
