name: hotel-id-nns
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - yapf
  - ca-certificates
  - openssl
  - torchvision
  - cpuonly
  - pytorch
  - pip>=22
  - dvc
  - dvc-ssh
  - sklearn
  - wandb
  - pip:
    - addict==2.4.0
    - click==8.1.3
    - contourpy==1.0.6
    - cycler==0.11.0
    - fonttools==4.38.0
    - kiwisolver==1.4.4
    - markdown==3.4.1
    - matplotlib==3.6.2
    - mmcv-full==1.7.0
    - mmdet==2.25.3
    - model-index==0.1.11
    - opencv-python==4.6.0.66
    - openmim==0.3.3
    - ordered-set==4.1.0
    - pandas==1.5.1
    - pycocotools==2.0.6
    - pytz==2022.6
    - terminaltables==3.1.10
    - tables
